# Generated by Django 3.2.9 on 2021-11-30 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_food_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.AddField(
            model_name='food',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
